// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLvWjyJpIqqAXZsmp6Fp4nBIkB9_Qvhhs',
    appId: '1:755058294755:web:115a7aaf646f46f3e42ad6',
    messagingSenderId: '755058294755',
    projectId: 'goonam-2b3a5',
    authDomain: 'goonam-2b3a5.firebaseapp.com',
    storageBucket: 'goonam-2b3a5.firebasestorage.app',
    measurementId: 'G-3S01JYKRKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsk0_CR3_Y75I0B11qlg63b4aroUWBN70',
    appId: '1:755058294755:android:11eb96920766395de42ad6',
    messagingSenderId: '755058294755',
    projectId: 'goonam-2b3a5',
    storageBucket: 'goonam-2b3a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPTB0Tz3cNQeHxD8RnjNSu3QvC73NMUqY',
    appId: '1:755058294755:ios:9c2d2ea5956e6cf7e42ad6',
    messagingSenderId: '755058294755',
    projectId: 'goonam-2b3a5',
    storageBucket: 'goonam-2b3a5.firebasestorage.app',
    iosBundleId: 'com.example.goonamManageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPTB0Tz3cNQeHxD8RnjNSu3QvC73NMUqY',
    appId: '1:755058294755:ios:9c2d2ea5956e6cf7e42ad6',
    messagingSenderId: '755058294755',
    projectId: 'goonam-2b3a5',
    storageBucket: 'goonam-2b3a5.firebasestorage.app',
    iosBundleId: 'com.example.goonamManageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLvWjyJpIqqAXZsmp6Fp4nBIkB9_Qvhhs',
    appId: '1:755058294755:web:ec513ea62fbf7a24e42ad6',
    messagingSenderId: '755058294755',
    projectId: 'goonam-2b3a5',
    authDomain: 'goonam-2b3a5.firebaseapp.com',
    storageBucket: 'goonam-2b3a5.firebasestorage.app',
    measurementId: 'G-RJ1BZ6KHS3',
  );
}
